"""empty message

Revision ID: 407b7aecc4a3
Revises: 816dbfc0a85a
Create Date: 2021-10-06 18:15:53.191299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407b7aecc4a3'
down_revision = '816dbfc0a85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.drop_column('waiting_screen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waiting_screen', sa.VARCHAR(length=20000), nullable=True))

    # ### end Alembic commands ###
