"""empty message

Revision ID: 6b4aa0ce5ac7
Revises: fac18f7b320f
Create Date: 2021-10-11 19:00:10.306884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4aa0ce5ac7'
down_revision = 'fac18f7b320f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActiveGames', schema=None) as batch_op:
        batch_op.drop_column('delta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActiveGames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delta', sa.VARCHAR(length=1000), nullable=True))

    # ### end Alembic commands ###
