"""empty message

Revision ID: 816dbfc0a85a
Revises: 862467b87fb1
Create Date: 2021-10-06 17:53:18.523879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816dbfc0a85a'
down_revision = '862467b87fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActiveGames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delta', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActiveGames', schema=None) as batch_op:
        batch_op.drop_column('delta')

    # ### end Alembic commands ###
