"""empty message

Revision ID: 862467b87fb1
Revises: e569359f9e5c
Create Date: 2021-10-04 19:52:33.553011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862467b87fb1'
down_revision = 'e569359f9e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActiveGames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_created', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActiveGames', schema=None) as batch_op:
        batch_op.drop_column('time_created')

    # ### end Alembic commands ###
