"""empty message

Revision ID: 8fbe0c04351d
Revises: 
Create Date: 2021-10-03 12:39:56.437943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbe0c04351d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EntityInstance', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EntityInstance', 'name')
    # ### end Alembic commands ###
