"""empty message

Revision ID: e569359f9e5c
Revises: f3ff9b96ac90
Create Date: 2021-10-03 18:20:14.969830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e569359f9e5c'
down_revision = 'f3ff9b96ac90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waiting_screen', sa.String(length=20000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.drop_column('waiting_screen')

    # ### end Alembic commands ###
