"""empty message

Revision ID: f3ff9b96ac90
Revises: 57936b9b013a
Create Date: 2021-10-03 15:22:10.731573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ff9b96ac90'
down_revision = '57936b9b013a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entity', schema=None) as batch_op:
        batch_op.create_unique_constraint('hash', ['hash'])

    with op.batch_alter_table('EntityInstance', schema=None) as batch_op:
        batch_op.create_unique_constraint('hash', ['hash'])

    with op.batch_alter_table('Map', schema=None) as batch_op:
        batch_op.create_unique_constraint('hash', ['hash'])

    with op.batch_alter_table('MapInstance', schema=None) as batch_op:
        batch_op.create_unique_constraint('hash', ['hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MapInstance', schema=None) as batch_op:
        batch_op.drop_constraint('hash', type_='unique')

    with op.batch_alter_table('Map', schema=None) as batch_op:
        batch_op.drop_constraint('hash', type_='unique')

    with op.batch_alter_table('EntityInstance', schema=None) as batch_op:
        batch_op.drop_constraint('hash', type_='unique')

    with op.batch_alter_table('Entity', schema=None) as batch_op:
        batch_op.drop_constraint('hash', type_='unique')

    # ### end Alembic commands ###
