"""empty message

Revision ID: fac18f7b320f
Revises: 407b7aecc4a3
Create Date: 2021-10-06 20:04:22.732008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac18f7b320f'
down_revision = '407b7aecc4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xcount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ycount', sa.Integer(), nullable=True))
        batch_op.drop_column('xsize')
        batch_op.drop_column('ysize')
        batch_op.drop_column('offset')
        batch_op.drop_column('scale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scale', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('offset', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('ysize', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('xsize', sa.INTEGER(), nullable=True))
        batch_op.drop_column('ycount')
        batch_op.drop_column('xcount')

    # ### end Alembic commands ###
